apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: moyuan-org-tls
spec:
  secretName: moyuan-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: moyuan.org
  dnsNames:
    - moyuan.org
    - www.moyuan.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - moyuan.org
          - www.moyuan.org
